apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /system/metrics
    prometheus.io/scrape: 'true'
  labels:
    app: {{ .Values.api.name }}
  name: {{ .Values.api.name }}
spec:
  ports:
    - name: {{ .Values.api.port | quote }}
      port: {{ .Values.api.port }}
      targetPort: 8080
  selector:
    app: {{ .Values.api.name }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.ui.name }}
  name: {{ .Values.ui.name }}
spec:
  ports:
    - name: {{ .Values.ui.port | quote }}
      port: {{ .Values.ui.port }}
      targetPort: 8080
  selector:
    app: {{ .Values.ui.name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: 'true'
  labels:
    app: {{ .Values.ws.name }}
  name: {{ .Values.ws.name }}
spec:
  ports:
    - name: {{ .Values.ws.port | quote }}
      port: {{ .Values.ws.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.ws.name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: 'mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}'
  labels:
    app: {{ .Values.database.name }}
  name: {{ .Values.database.name }}
spec:
  ports:
    - name: mysql
      port: {{ .Values.database.port }}
      targetPort: 3306
  selector:
    app: {{ .Values.database.name }}
