apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.ws.name }}
    app.kubernetes.io/part-of: apicurio
  name: {{ .Values.ws.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ws.name }}
      deploymentconfig: {{ .Values.ws.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ws.name }}
        deploymentconfig: {{ .Values.ws.name }}
    spec:
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1800Mi
            requests:
              cpu: 100m
              memory: 900Mi
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
          {{- if .Values.loggingEnabled }}
          - name: APICURIO_LOGGING_LEVEL
            value: debug
          {{- end }}
          - name: APICURIO_DB_CONNECTION_URL
            value: {{ .Values.keycloak.url }}
          - name: APICURIO_DB_DRIVER_NAME
            value: {{ .Values.database.driver }}
          - name: APICURIO_DB_INITIALIZE
            value: {{ .Values.database.initialize | quote }}
          - name: APICURIO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: apicurio-secret
                key: db-password
          - name: APICURIO_DB_TYPE
            value: {{ .Values.database.type }}
          - name: APICURIO_DB_USER_NAME
            valueFrom:
              secretKeyRef:
                name: apicurio-secret
                key: db-user
          - name: APICURIO_SHARE_FOR_EVERYONE
            value: {{ .Values.uiFeatureShareForEveryone | quote }}
          - name: JAVA_TOOL_OPTIONS
            value: {{ .Values.ws.jvmArgs }}
          image: {{ .Values.ws.image }}
          imagePullPolicy: {{ .Values.ws.imagePullPolicy }}
          name: {{ .Values.ws.name }}
          ports:
            - containerPort: 8080
      restartPolicy: Always