kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    container: spring
    group: {{ .Values.name }}
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: spring
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: {{ .Values.name }}
    container: spring
    group: {{ .Values.name }}
