apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: {{ .Values.name }}-mongodb
  labels:
    app: {{ .Values.name }}
    container: mongodb
    group: {{ .Values.name }}
stringData:
  database-admin-password: {{ .Values.mongodb.adminPass | quote }}
  database-name: {{ .Values.mongodb.database | quote }}
  database-password: {{ .Values.mongodb.pass | quote }}
  database-user: {{ .Values.mongodb.user | quote }}
