apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-postman-runtime
  labels:
    app: {{ .Values.name }}
    container: postman-runtime
    group: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    app: {{ .Values.name }}
    deploymentconfig: {{ .Values.name }}-postman-runtime
    container: postman-runtime
    group: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        deploymentconfig: {{ .Values.name }}-postman-runtime
        container: postman-runtime
        group: {{ .Values.name }}
    spec:
      containers:
      - name: postman-runtime
        image: {{ .Values.postman.image.repo }}:{{ .Values.postman.image.tag | default "latest" }}
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value: info
        resources:
          limits:
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: "/health"
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 4
          timeoutSeconds: 3
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/health"
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
