kind: Service
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-uri: 'mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}'
  name: {{ .Values.name }}-mongodb
  labels:
    app: {{ .Values.name }}
    container: mongodb
    group: {{ .Values.name }}
spec:
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: {{ .Values.name }}
    container: mongodb
    group: {{ .Values.name }}
  type: ClusterIP
  sessionAffinity: None
