apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.size | quote }}
