apiVersion: v1
kind: Deployment
metadata:
  labels:
    application: {{ .Values.appName }}
  name: {{ .Values.appName }}-postgresql
spec:
  replicas: 1
  selector:
    app: {{ .Values.appName }}-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: {{ .Values.appName }}
        deployment: {{ .Values.appName }}-postgresql
      name: {{ .Values.appName }}-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: {{ .Values.database.username }}
        - name: POSTGRESQL_PASSWORD
          value: {{ .Values.database.password }}
        - name: POSTGRESQL_DATABASE
          value: {{ .Values.database.name }}
        - name: POSTGRESQL_MAX_CONNECTIONS
          value: {{ .Values.postgres.max_connections }}
        - name: POSTGRESQL_MAX_PREPARED_TRANSACTIONS
          value: {{ .Values.postgres.max_connections }}
        - name: POSTGRESQL_SHARED_BUFFERS
          value: {{ .Values.postgres.shared_buffers }}
        image: postgresql
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 90
          successThreshold: 1
          tcpSocket:
            port: {{ .Values.postgres.port }}
          timeoutSeconds: 10
        name: {{ .Values.appName }}-postgresql
        ports:
        - containerPort: {{ .Values.postgres.port }}
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
              'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 90
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: {{ .Values.postgres.port }}-postgresql-pvol
      terminationGracePeriodSeconds: 60
      volumes:
      - name: {{ .Values.appName }}-postgresql-pvol
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}-postgresql-claim