{{- if .Values.postgres }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    application: {{ .Values.appName }}
  name: {{ .Values.appName }}-postgresql-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.volume_capacity }}