{{- if .Values.svc }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.svc.http_port }}
    targetPort: {{ .Values.svc.http_port }}
  selector:
    application: {{ .Values.appName }}