{{- if .Values.svc }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's https port.
  labels:
    application: {{ .Values.appName }}
  name: secure-{{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.svc.https_port }}
    targetPort: {{ .Values.svc.https_port }}
  selector:
    application: {{ .Values.appName }}
{{- end }}
