apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's https port.
    service.alpha.openshift.io/dependencies: '[{"name": "{{ .Values.name }}-postgresql", "kind": "Service"}]'
    service.alpha.openshift.io/serving-cert-secret-name: sso-x509-https-secret
  labels:
    application: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
    - port: 8443
      targetPort: 8443
  selector:
    deploymentConfig: {{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The database server's port.
  labels:
    application: {{ .Values.name }}
  name: {{ .Values.name }}-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    deploymentConfig: {{ .Values.name }}-postgresql
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The JGroups ping port for clustering.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
    service.alpha.openshift.io/serving-cert-secret-name: sso-x509-jgroups-secret
  labels:
    application: {{ .Values.name }}
  name: {{ .Values.name }}-ping
spec:
  clusterIP: None
  ports:
    - name: ping
      port: 8888
  selector:
    deploymentConfig: {{ .Values.name }}
