apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    description: ConfigMap providing service ca bundle.
    service.beta.openshift.io/inject-cabundle: 'true'
  labels:
    application: {{ .Values.name }}
  name: {{ .Values.name }}-service-ca
