apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    application: {{ .Values.name }}
  name: {{ .Values.name }}-postgresql-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.size | quote }}
