apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: {{ .Values.name }}
  name: {{ .Values.name }}-postgresql
spec:
  replicas: 1
  selector:
    deploymentConfig: {{ .Values.name }}-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: {{ .Values.name }}
        deploymentConfig: {{ .Values.name }}-postgresql
      name: {{ .Values.name }}-postgresql
    spec:
      containers:
        - env:
            - name: POSTGRESQL_USER
              value: {{ .Values.database.user | quote }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.database.pass | quote }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.database.name | quote }}
            - name: POSTGRESQL_MAX_CONNECTIONS
            - name: POSTGRESQL_MAX_PREPARED_TRANSACTIONS
            - name: POSTGRESQL_SHARED_BUFFERS
          image: postgresql
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 90
            'successThreshold:': 1
            tcpSocket:
              port: 5432
            timeoutSeconds: 10
          name: {{ .Values.name }}-postgresql
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d
                  $POSTGRESQL_DATABASE -c 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 90
            'successThreshold:': 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: {{ .Values.name }}-postgresql-pvol
      terminationGracePeriodSeconds: 60
      volumes:
        - name: {{ .Values.name }}-postgresql-pvol
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-postgresql-claim
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - {{ .Values.name }}-postgresql
        from:
          kind: ImageStreamTag
          name: 'postgresql:10'
          namespace: {{ .Values.imagestream.namespace }}
      type: ImageChange
    - type: ConfigChange
