name: microcks
host: microcks-test-charts.apps.s45.core.rht-labs.com

resources:
  limits:
    memory: "512Mi"

image:
  repo: quay.io/microcks/microcks
  tag: nightly

postman:
  image:
    repo: quay.io/microcks/microcks-postman-runtime
    tag: latest

mongodb:
  version: "3.6"
  adminPass: root
  user: microcks
  pass: microcks
  database: microcks
  size: "1Gi"
  resources:
    limits:
      memory: "512Mi"

keycloack:
  host: https://sso-test-charts.apps.s45.core.rht-labs.com
