api:
  name: apicurio-studio-api
  image: apicurio/apicurio-studio-api
  jvmArgs: -Djava.net.preferIPv4Stack=true
  port: 8091
  imagePullPolicy: IfNotPresent

ui:
  name: apicurio-studio-ui
  image: apicurio/apicurio-studio-ui
  jvmArgs: -Djava.net.preferIPv4Stack=true
  port: 8093
  imagePullPolicy: IfNotPresent
  logout:
    redirect:
      uri: "/"
  hub:
    api:
      # url to hub api
      url: https://apicurio-studio-api-test-charts.apps.s45.core.rht-labs.com
  editing:
    # url to editing
    url: wss://apicurio-studio-ws-test-charts.apps.s45.core.rht-labs.com
  feature:
    microcks: false

ws:
  name: apicurio-studio-ws
  image: apicurio/apicurio-studio-ws
  jvmArgs: -Djava.net.preferIPv4Stack=true
  port: 8092
  imagePullPolicy: IfNotPresent

database:
  name: apicurio-studio-db
  version: "8.0"
  port: 3306
  imagePullPolicy: IfNotPresent
  initialize: true
  driver: mysql
  type: mysql5
  url: jdbc:mysql://apicurio-studio-db:3306/apicuriodb
  schema: apicuriodb
  #default passwords and user
  password: apicuriodb
  rootPassword: apicuriodb
  user: apicuriodb

uiFeatureShareForEveryone: true
loggingEnabled: false

#Configure microcks application
microcks:
  api:
    # url to mickrocks application
    url: https://microcks-test-charts.apps.s45.core.rht-labs.com/api
  realm: microcks
  client:
    id: microcks-serviceaccount
    #default secret
    secret: "27a85ae0-0434-49a3-bcde-dc5197a8ccbd"

#Configure keycloak application
keycloak:
  # url to keycloak app
  url: https://sso-test-charts.apps.s45.core.rht-labs.com
  realm: apicurio
  client:
    id: apicurio-studio
    #default secret
    secret: apicuriokc
